[global]
type=global

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[kamailio]
type=endpoint
context=tas-inbound
disallow=all
allow=ulaw
allow=alaw
aors=kamailio

[kamailio]
type=aor
contact=sip:kamailio:5060

[kamailio]
type=identify
endpoint=kamailio
match=kamailio
